# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

# Site settings
title: "HELLO"
description: > # this means to ignore newlines until "email:"


email: twipixel@gmail.com
#blog logo
logo: "/assets/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/bg.png"

name: 'twipixel'
author: 'twipixel'
author_image: "/assets/author.png"

paginate:	5

url: "http://twipixel.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@playtwip'

#fill in disqus shortname to use disqus
disqus: twipixel

google_analytics: UA-93357933-1

timezone: "Asia/Seoul"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/playtwip
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/twipixel
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/twipixel
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
